version: '3.4'

services:

  mariadb:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tolentinos123
      MYSQL_DATABASE: tolentinos
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "16379:6379"
    networks:
      - backend

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge